
FROM node:16

# Create app directory /usr/src
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY ./server/package*.json ./

RUN npm install

# Bundle app source
COPY ./server .

EXPOSE 4000
CMD [ "node", "server.js" ]