
FROM node:16

# Create app directory /usr/src
WORKDIR /app

COPY ./client/public ./public
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY ./client/package*.json ./

RUN npm install

RUN apt-get update && apt-get install nano

# Bundle app source
COPY ./client/src ./src

EXPOSE 3000
CMD [ "npm", "start" ]